name: Frist Workflow 
on: [push]
jobs:
  Run-Shell-command:
    runs-on: ubuntu-latest
    steps:
        - Name: Run a one-line script
          run: echo Hello, world!
        - Name: Run a multi-line script
            run: |
                node -v
                npm -v