name: Frist Workflow 
on: [push]
jobs:
  Run-Shell-command:
    runs-on: ubuntu-latest
    steps:
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
                node -v
                npm -v
  Parallel-Job:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  depandent-job:
    needs: [Run-Shell-command]
    runs-on: windows-latest
    steps:
      - name: echo String
        run: write-Host "Hello from Windows"
      - name: Error Step
        run: doesnotexist